from pathlib import Path
CONTENT_DIR = Path(r"C:\Users\Axeno\Desktop\UP-PCS\mains-pyqs\_content_sections")

EXTRA = {
"03_Poverty_Causes_Consequences.md": """
### Additional depth — consequences and human capital

Consequences ripple across generations: malnourished child (NFHS stunting) underperforms in school, exits early for labour, earns low wage, cannot invest in own children — intergenerational trap closes. Social consequences include political clientelism where poor depend on patron for ration and loans, weakening demand for structural reform. Gender violence intensifies with economic dependency — dowry demands scale with aspirational consumption even among poor households. Urban slums (Dharavi, Kanpur tannery belt) concentrate poverty spatially — informal sector working poor invisible in unemployment statistics. Political voicelessness means policies designed without poor participation — Aadhaar-DBT exclusion errors hit most vulnerable. Medical poverty remains leading descent route — one hospitalization can erase MGNREGA savings without PM-JAY cover in unregistered facilities. Climate shocks (drought in Bundelkhand, flood in Bihar) push near-poor below line seasonally — poverty is dynamic, not static snapshot. Rangarajan line debate matters because near-poor above Tendulkar remain vulnerable — MPI captures this better than single income threshold.
""",
"04_Urbanization_Slums_Remedies.md": """
### Additional depth — governance, migration, and SDG 11

Urban governance failure explains why migration produces slums: master plans ignore migrant housing need; ULBs lack revenue for sewerage extension to informal settlements; 74th Amendment devolution incomplete — mayor lacks authority in many states including UP; ward committees underutilized. Distress migration differs from voluntary urbanization — push factors (drought, land fragmentation, caste oppression in village) dominate for poorest migrants, not pull of glamour. Peri-urban fringe (Sitapur-Lucknow, Ghaziabad-Meerut) grows without municipal status — people live urban lives with rural governance, worst of both worlds. Gender dimension: urban poor women face double burden — domestic work plus wage labour plus unsafe public transport. Child impact: slum children lack playgrounds, face school dropout for family income, vulnerable to trafficking. SDG 11 targets inclusive, safe, resilient cities — India's performance mixed: smart city pockets amid vast underserved wards. Street Vendors Act 2014 protection often unimplemented — hawker eviction cycles repeat. Climate adaptation: urban heat action plans needed for tin-roof slums; drainage upgrade prevents repeat of 2023 Delhi-Chennai scenes. Regional planning: invest in Kanpur, Varanasi, Agra as tier-2 hubs to absorb UP migration without NCR overload.
""",
"01_LPG_Effects_India.md": """
### Additional depth — globalization sociological frameworks and proof points

Yogendra Singh's modernization of tradition explains why LPG did not erase caste or joint family — differentiated structure where market criteria overlay ritual hierarchy. Srinivas: sanskritization (emulate upper ritual) and westernization (emulate Western lifestyle) operate simultaneously among upwardly mobile groups — hybrid identity. Little and great tradition: village oral culture absorbs Bollywood and WhatsApp — global media localized. Anti-globalization movements: Narmada Bachao linked displacement to development model; WTO Seattle 1999 inspired Indian farmer-labour skepticism of free trade. Consumer culture: mall revolution, credit card debt, festival marketing — tyaga ethic strained. Diaspora reverse flow: Silicon Valley CEOs, Diwali in White House, yoga diplomacy — integration export. Backlash: ghar wapsi debates, book bans, anti-Valentine squads — conflict export. WTO fishery subsidy negotiation affects Kerala coastal communities — globalization reaches fishing villages not only IT parks. Gig economy: Swiggy-Zomato riders — new informal proletariat without labour code social security fully operationalized. Proof for women answer: TCS and Infosys campus recruitment of women engineers versus Tamil Nadu garment belt sweatshops — same globalization, opposite outcomes by class and geography.
""",
"02_Modernization_Westernization.md": """
### Additional depth — value clusters under pressure and education stress

Dharma under pressure: market rationality measures success by income not righteous conduct — yet dharma discourse persists in politics (Ram Mandir, ethical AI debates invoking Indian philosophy). Ahimsa under pressure: industrial extraction, factory farming, communal violence — yet Gandhi's legacy invoked in environmental and peace movements. Joint family under pressure: nuclear residence but joint responsibility during crisis — festival economy and wedding networks maintain kin collectivity. Vasudhaiva kutumbakam revived in Vaccine Maitri diplomacy — traditional value repurposed for global age. Guru-shishya parampara under pressure: YouTube replaces ashram for classical music learning — continuity through new medium. Western education mental health crisis: Kota suicides, NEET pressure, coaching class dominance — LPG-era hyper-competition damages youth; NEP 2020 holistic education response. Ashis Nandy warns homogenizing modernity erases plural knowledge — IKS revival is intellectual counter-movement. Periyar and Ambedkar used modernity against traditional hierarchy — modernization can be emancipatory not only destructive. Comparative: Turkey, Indonesia — Muslim-majority nations combining faith and modern institutions — India comparable selective synthesis path.
""",
"03_Globalization_Social_Institutions.md": """
### Additional depth — sociologists, laws, and proof for each institution

Irawati Karve's regional kinship geography remains valid despite globalization — marriage rules differ north-south-tribal; migration loosens enforcement but does not erase preference. A.M. Shah documented joint family as ideology persisting after practice nuclearized — ideological continuity matters for ritual and inheritance disputes. Patricia Uberoi analyzed family in Asia under global capital — Indian marriage becomes transaction involving global flows (NRI groom, dollar dowry, foreign education premium). Roland Lardinois on Indian family modernity — conjugality rises but embedded in kin network approval. Hindu Marriage Act 1955 monogamy and judicial divorce enabled urban mutual consent exits. Muslim Women Act 2019 criminalized instant triple talaq — global feminist pressure plus domestic mobilization. Special Marriage Act 1954 enables civil inter-faith union against communal pressure — globalization of cosmopolitan identity meets local majoritarianism. Domestic Violence Act 2005 covers live-in — partial legal recognition of non-marital cohabitation. Puttaswamy 2017 privacy fundamentality supports marital autonomy arguments. Supreme Court same-sex marriage petition 2023 — global LGBTQ human rights discourse meets Indian kinship law — pending institutional adaptation. Proof points: Census household size decline; NFHS later marriage age; Shaadi.com caste filter screenshots in sociological studies; remittance architecture in Kerala and UP villages; COVID digital wedding normalization.
""",
"01_Regionalism.md": """
### Additional depth — water, coalitions, and comparative federalism

Inter-state water disputes embody regionalism economically: Cauvery affects Tamil Nadu paddy and Karnataka sugarcane; Krishna-Godavari tribunal awards contested; Narmada benefits Gujarat-Madhya Pradesh but displaced tribal regions protest — development regionalism not only language politics. Coalition era 1990s–2010s: national policy (economic reforms, nuclear deal) negotiated with DMK, TDP, Left — regional parties as veto players — democratic deepening or paralysis depending on accommodation quality. Vibrant Gujarat versus Bihar model — competitive federalism compares state GDP strategies — regional pride instrument for investment marketing. North-East: AFSPA, insurgency, Act East connectivity — regionalism as security and development intersection; Sixth Schedule autonomy as opportunity framework. Hindi imposition protests: Tamil Nadu 1965 legacy repeats in NEET-JEE language row, NEP three-language formula resistance — cultural regionalism against perceived gangetic core dominance. Comparative: Spain (Catalonia), Canada (Quebec) — India managed similar pressures through linguistic states and Article 3 flexibility better than many federations — proof for optimistic integration argument. Fazl Ali Commission (States Reorganisation) historical anchor — linguistic principle chosen over economic or administrative convenience — foundational decision enabling today's federal stability.
""",
"02_Secularism_Communalism.md": """
### Additional depth — thinkers, commissions, and constitutional morality

Asghar Ali Engineer documented communal riots as political engineering rooted in economic rivalry between communities — shopkeepers, slum land, municipal contracts. Bipan Chandra distinguished communalism from communal consciousness and communal violence — ideology versus identity versus event. Sachar Committee (2006) proved Muslim socio-economic marginalization — relative deprivation feeds grievance exploitable by communal politics; not communalism cause alone but structural context. National Commission for Minorities (1992) monitors welfare — institutional secular practice. Shah Bano (1985) and subsequent legislative response showed tension between uniform civil reform and minority personal law — secularism debate concrete not abstract. Babri Masjid-Ram Janmabhoomi dispute decades-long — constitutional secularism tested by faith-based territorial claims — Ayodhya judgment 2019 attempted legal closure. Hate speech jurisprudence evolving — Supreme Court 2023–24 directives on rumour and inflammatory media — digital communalism new production chain link. Electoral bonds judgment 2024 — opaque political finance enables communal campaign funding — governance reform secular practice. Composite nationalism: Freedom Movement united Hindus-Muslims-Sikhs against colonial divide-and-rule — historical proof integration possible. Gandhi's assassination by communal fanatic proves cost of failing secular fraternity — existential stakes for liberal democracy.
""",
"03_Social_Empowerment.md": """
### Additional depth — SC/OBC/women intersection and digital governance

Social empowerment not ST-only though 2019 PYQ focuses ST: SC communities face untouchability despite Art 17 — PoA Act 1989 enforcement gaps; manual scavenging prohibition incomplete. OBC mobilization post-Mandal — political empowerment without full economic transformation for many jatis. Women: social empowerment prerequisite for inclusive development (2021 logic) — applies across groups. Disabled: RPwD Act 2016 rights awareness growing — accessibility in digital governance uneven. Minorities: Sachar deprivation limits economic empowerment despite formal citizenship. Common Service Centres (CSCs) — 5 lakh village-level entrepreneurs deliver PAN, passport, pension services — digital last mile; VLE income model empowers rural youth operator class. DIKSHA and SWAYAM MOOCs — education empowerment during COVID school closure. MyGov participatory platforms — weak but direction toward digital citizenship. Cybercrime against women and children — CCPWC scheme — digital disempowerment counter-current. Blockchain land records pilots — potential ST land titling transparency if scaled with FRA. Evaluation template: name channel (RTI, DBT, UPI), state benefit, cite limit (divide, exclusion, misinformation), conclude IT multiplies structural empowerment never replaces it. PM-JANMAN 100-day sprint for PVTG — 2023–24 contemporary anchor for tribal digital-health-housing integration.
""",
}

for fname, block in EXTRA.items():
    path = CONTENT_DIR / fname
    text = path.read_text(encoding="utf-8")
    marker = "### Limits and balanced view"
    if block.strip() not in text:
        text = text.replace(marker, block.strip() + "\n\n" + marker)
        path.write_text(text, encoding="utf-8")
        print("Round3:", fname)
