from pathlib import Path
CONTENT_DIR = Path(r"C:\Users\Axeno\Desktop\UP-PCS\mains-pyqs\_content_sections")

FINAL = {
"04_Urbanization_Slums_Remedies.md": "Urbanization in India cannot be reduced to Smart Cities Mission showcase pockets — majority urban residents live in wards without piped sewerage, reliable water, or formal tenure. The 2025 PYQ pairing socio-economic problems with structural measures demands institutional analysis: without ULB revenue autonomy and enforced master plans, AMRUT and PMAY disbursements treat symptoms while land speculation and migrant influx recreate slums elsewhere. Inclusive urbanization means portable welfare (ONORC ration, e-Shram registration at destination), vendor legalization, and climate-resilient drainage — not only concrete and metro rails.",
"01_LPG_Effects_India.md": "LPG answers must always balance: IT boom and consumer choice alongside farmer distress and gig precarity; diaspora soft power alongside tribal displacement; regulatory modernization alongside crony capitalism allegations. Name institutions — SEBI, TRAI, WTO, IMF 1991, MGNREGA offset — for credibility. Yogendra Singh and Srinivas frameworks distinguish social-structure answers from pure economic narration. Cultural integration AND conflict both mandatory in 2025 globalization-cultural question.",
"02_Modernization_Westernization.md": "Critical evaluate answers on traditional values require named proof: sati abolition (modern law vs traditional practice), joint family nuclearization (Census household size), English premium (NEP multilingual response), IKS revival (Ayurveda in NEP), mental health crisis (Kota coaching). Distinguish modernization from westernization explicitly — Panchayati Raj and ISRO are modern Indian institutions without Western lifestyle mimicry. Gandhi and Tagore offer indigenous critiques of colonial education — not only Western import story.",
"03_Globalization_Social_Institutions.md": "2025 PYQ on family-marriage-kinship requires tri-partite structure with Indian proof in each: family nuclearization (Bangalore IT migrants), marriage apps with caste filters (Shaadi.com), kinship remittance authority (Gulf NRIs in Kerala and UP villages). Cite NFHS-5 for marriage age, HMA 1955 for divorce, DV Act 2005 for live-in, Karve for regional kinship. Conclude adaptive continuity — globalization modifies intensity of kin obligations without dissolving marriage as central institution.",
"01_Regionalism.md": "Every regionalism answer needs challenge-opportunity duality with named cases: 1965 Tamil anti-Hindi (accommodation), Telangana 2014 (Art 3), Cauvery (hindrance), Shiv Sena son-of-soil (exclusion challenge), Ek Bharat Shreshtha Bharat (positive integration). Rajni Kothari Congress breakdown explains polity regionalization. Economy section: GST Council, investment summits, labour migration from UP-Bihar. Integration: civic nationalism versus ethnic nationalism — Constitution binds diversity if regions feel respected.",
"02_Secularism_Communalism.md": "Secularism answers anchor on Art 25-28, Preamble Secular (42nd Amendment 1976), sarva dharma sambhava, Bhargava contextual model — not French laïcité. Communalism: Bipan Chandra political instrument; Brass riot production chain with 1984/1992/2002/2013/2020 examples. Nation-civic Art 1 versus communal distortion; CAA debate contemporary stress test. 2019 statement: partial truth — secular boundaries contested but violence serves power primarily. Composite culture and institutional safeguards (NCM, NHRC) strengthen balanced conclusions.",
"03_Social_Empowerment.md": "IT empowerment evaluation template: channel (RTI/DBT/UPI/telemedicine) + benefit + digital divide limit. ST barriers: FRA-PESA synergy on paper, implementation failure on ground; PM-JANMAN for PVTG; TRIFED MSP; EMRS education; mining displacement in Odisha-Chhattisgarh. Reservation necessary not sufficient — land, health, education, anti-atrocity enforcement equally critical. Heterogeneous 705 ST groups — avoid monolithic answer. Social empowerment spans SC/OBC/women/disabled — not ST-only though 2019 PYQ focuses tribal barriers.",
}

for fname, para in FINAL.items():
    path = CONTENT_DIR / fname
    text = path.read_text(encoding="utf-8")
    if para not in text:
        text = text.replace("### Limits and balanced view", para + "\n\n### Limits and balanced view")
        path.write_text(text, encoding="utf-8")
